language: node_js
node_js:
  - "8"
  - "9"

dist: trusty
sudo: false
cache: yarn
# S: Build Lifecycle
install:
- yarn

script:
- yarn global add typescript
- echo "export const ACCESS_KEY :string = "FOO"\n export const SECRET_KEY :string = "COOL"" >> ./src/config/aws-key.ts
- tsc
