language: node_js
node_js:
  - "8"
  - "9"

dist: trusty
sudo: false
cache: yarn
# S: Build Lifecycle
install:
- yarn

script:
- yarn global add typescript
- cd ./src/config
- wget https://gist.githubusercontent.com/frankwei98/df0bcf18f2ad77d32b6245eeaa9be6a5/raw/3964a3a0ad9370d6ac0e28f5d1d3ba7f5e564789/aws-key.ts
- cd ../../
- tsc
